### ISSUE TITLE
プレハブを加えると、レンダリングに異常が生じる

### ISSUE THREAD

**Issue by miurror** [scienceagora4dim/Stereoscopic4D#1]
Demo Sceneに新しくTesseractのprefabを加えるとレンダリングに異常が生じる。

具体的には、たとえば追加したprefabのx座標を0でない値に設定すると、
カメラの位置が逆方向に移動したようにレンダリングされる。
また、この際、4次元方向の回転操作がただの3次元回転として反映されてしまう。

**Comment by outlandkarasu** [comment]
Componentに紐づけられたMaterialのInstanceではなくMaterial本体の方のAttributesを変更してしまっていたというバグがあったようです（汗）。

http://answers.unity3d.com/questions/36011/different-shader-parameters-for-instances-of-a-mat.html

修正を行ったので、masterへrebaseして確認をお願いします!
